### ISSUE TITLE
Update to 4.0 (Release v3.2)

### ISSUE THREAD

**Issue by monrealis** [Hubbitus/Docker-art#1]
Could you please release v3.2 to dockerhub (https://hub.docker.com/r/hubbitus/docker-art/)?

**Comment by Hubbitus** [comment]
Update with temporary patch. See corresponded MR: https://sourceforge.net/p/art/code/merge-requests/12/

**Comment by Hubbitus** [comment]
Please try new update: https://hub.docker.com/r/hubbitus/art
